reddit/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index]

end

reddit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit/app/models/post.rb
class Post < ApplicationRecord

belongs_to :user
has_many :post_subs

has_many :subs,
through: :post_subs,
source: :sub

validates :title, presence: true

end

reddit/app/models/post_sub.rb
class PostSub < ApplicationRecord

belongs_to :post
belongs_to :sub

end

reddit/app/models/sub.rb
class Sub < ApplicationRecord

  belongs_to :moderator,
  foreign_key: :user_id,
  class_name: :User

  has_many :post_subs

  has_many :posts,
  through: :post_subs,
  source: :post

  validates :title, presence: true




end

reddit/app/models/user.rb
class User < ApplicationRecord
validates :username,:password_digest,presence: true
validates :password,length: {minimum:6, allow_nil: true}
before_validation :ensure_session_token
attr_reader :password

has_many :subs

has_many :posts

def self.find_by_credentials(username,password)
  user = User.find_by(username: username)
  user && user.is_password?(password) ? user : nil
end

def is_password?(password)

  BCrypt::Password.new(self.password_digest).is_password?(password)
end

def password=(password)
  @password = password
  self.password_digest = BCrypt::Password.create(password)
end

def ensure_session_token
  self.session_token ||= SecureRandom.urlsafe_base64
end

def reset_session_token!
  self.session_token = SecureRandom.urlsafe_base64
  self.save
  self.session_token
end

end

reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def login(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end
end

reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id


    if @post.save
      params[:post][:sub_ids].each do |sub_id|
        PostSub.create!(post_id: @post.id, sub_id: sub_id)
      end

      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_url
  end

  def show
    @post = Post.find(params[:id])

  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_id:[])
  end
end

reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if user
      login(user)
      redirect_to subs_url
    else
      flash[:errors] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = current_user.subs.find(params[:id])

    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end 
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create

    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

reddit/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit/app/helpers/posts_helper.rb
module PostsHelper
end

reddit/app/helpers/subs_helper.rb
module SubsHelper
end

reddit/app/helpers/users_helper.rb
module UsersHelper
end

reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%if logged_in? %>
      <%= current_user.username %>
      <form action="<%=session_url%>" method="post">
      <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" name="" value="Sign out">
      </form>
    <%end%>
    <%= yield %>
    <
  </body>
</html>

reddit/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<form  action="<%=posts_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label>Title
    <input type="text" name="post[title]" value="<%=@post.title%>">
  </label>
  <label>Content
    <textarea name="post[content]"><%=@post.title%></textarea>
  </label>
  <label>URL
    <input type="text" name="post[url]" value="<%=@post.url%>">
  </label>
  <%Sub.all.each do |subbed|%>
  <label>Sub IDS
    <input
    type="checkbox"
    name="post[sub_ids][]"
    value="<%=subbed.id%>"
    <%= "checked" if @post.sub_ids.include?(subbed.id) %>><%=subbed.title%>
  </label>
  <%end%>
  <input type="submit" name="" value="Edit Post">

</form>

reddit/app/views/posts/new.html.erb
<h1>New Post</h1>
<form  action="<%=posts_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label>Title
    <input type="text" name="post[title]" value="">
  </label>
  <label>Content
    <textarea name="post[content]"></textarea>
  </label>
  <label>URL
    <input type="text" name="post[url]" value="">
  </label>
  <%Sub.all.each do |subbed|%>
  <label>Sub IDS
    <input type="checkbox" name="post[sub_ids][]" value="<%=subbed.id%>"><%=subbed.title%>
  </label>
  <%end%>
  <input type="submit" name="" value="Sign Up">

</form>

reddit/app/views/posts/show.html.erb
<%= @post.title %>
<br>
<%= @post.content %>
<br>
<%= @post.url %>
<br>

<% @post.subs.each do |subb| %>
   <%= subb.title %>
<%end%>

reddit/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>
<form  action="<%=sub_url(@sub)%>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label>Title
    <input type="text" name="sub[title]" value="<%=@sub.title%>">
  </label>
  <label>Description
    <input type="text" name="sub[description]" value="<%=@sub.description%>">
  </label>
  <input type="submit" name="" value="Edit Sub">

</form>

reddit/app/views/subs/index.html.erb
<% @subs.each do |subbed| %>
<%= subbed.title %>
<%end%>

reddit/app/views/subs/new.html.erb
<h1>Create Sub</h1>
<form  action="<%=subs_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label>Title
    <input type="text" name="sub[title]" value="">
  </label>
  <label>Description
    <input type="text" name="sub[description]" value="">
  </label>
  <input type="submit" name="" value="Create Sub">

</form>

reddit/app/views/subs/show.html.erb
<h1>Subs#show</h1>
<p>Find me in app/views/subs/show.html.erb</p>

reddit/app/views/users/new.html.erb
<h1>Sign Up</h1>
<form  action="<%=users_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label>Username
    <input type="text" name="user[username]" value="">
  </label>
  <label>Password
    <input type="text" name="user[password]" value="">
  </label>
  <input type="submit" name="" value="Sign Up">

</form>